SOLVER:
  gpu: 0,
  logdir: logs/seg/02691156_airplane
  run: train
  max_epoch: 300
  test_every_epoch: 5
  step_size: (120,180,240)
  ckpt_num: 20


DATA:
  train:
    distort: True
    depth: 6
    angle: (0, 5, 0)
    interval: (1, 1, 1)
    scale: 0.25
    jitter: 0.25
    uniform: True
    node_dis: True
    location: data/shapenet_segmentation/points
    filelist: data/shapenet_segmentation/train_test_split/02691156_train_val.txt
    batch_size: 32
    shuffle: True

  test: 
    distort: False  # no data augmentation
    depth: 6
    node_dis: True
    location: data/shapenet_segmentation/points
    filelist: data/shapenet_segmentation/train_test_split/02691156_test.txt
    batch_size: 1
    shuffle: False


MODEL:
  name: segnet
  channel: 4
  nout: 4
  depth: 6


LOSS:
  mask: -1
  point_wise: True  
  num_class: 4
